baseURL = 'http://example.org/'
languageCode = 'pt-br'
title = 'Ofertas Mágicas'
theme = "ganimedes"
sectionPagesMenu = "menu"

[menu]
  [[menu.main]]
    name = "Início"
    pre = "welcome_message"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Produtos"
    pre = "produtos"
    url = "/products/"
    weight = 2