baseURL = 'http://www.ofertasmagicas.net/'
languageCode = 'pt-br'
title = 'Ofertas Mágicas'
theme = "ganimedes"
sectionPagesMenu = "menu"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Início"
    pre = "/"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Produtos"
    pre = "/#produtos"
    url = "/products/"
    weight = 2